---
name: Text-Pipe-RandomCase
version: 0.01
author:
  - 'Mario Domgoergen <mdom@cpan.org>'
abstract: Text::Pipe filter to randomize character case
license: perl
resources:
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mdom/text-pipe-randomcase
build_requires:
  Test::More: 0
requires:
  parent: 0
configure_requires:
  Module::Build: 0.35
provides:
  Text::Pipe::RandomCase:
    file: lib/Text/Pipe/RandomCase.pm
    version: 0.01
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
